name: GraalVM Native Image builds

on: push

jobs:
  build:
    name: Optimize-to-xes on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
        name: Build native-image
      - run: mvn -Pnative native:compile
      - run: java -Dspring.aot.enabled=true -agentlib:native-image-agent=config-output-dir=./src/main/resources/META-INF/native-image -Doptimize.base-url="$BASE_URL" -Doptimize.report-id="$REPORT_ID" -Doptimize.client-id="$CLIENT_ID" -Doptimize.client-secret="$CLIENT_SECRET" -Dxes-mapping.base-path="target" -jar target/optimize-to-xes-0.3.0-SNAPSHOT.jar
      - run: mvn -Pnative native:compile

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: optimize-to-xes-${{ matrix.os }}
          path: target/optimize-to-xes*
